name=Mouse
version=1.0.0
author=UIAP
maintainer=UIAP
sentence=Allows UIAPduino KBD+Mouse board to act as a USB mouse.
paragraph=Use with HID ProMicro CH32V003 KBD+Mouse board only.
category=Device Control
url=
architectures=ch32v
includes=Mouse.h
