name=HID
version=0.1.0
author=Tarosay
maintainer=Tarosay <tarosa.y@gmail.com>
sentence=HID support library for UIAPduino HID boards
paragraph=Provides HID support for UIAPduino HID boards based on the ch32v architecture.
category=Communication
url=https://github.com/tarosay/arduino_core_ch32
architectures=ch32v
