name=WebHID
version=1.0.0
author=UIAP
maintainer=UIAP
sentence=WebHID bidirectional communication for UIAPduino KBD+Mouse+Web board.
paragraph=Use with Board Version: V1.4 + WebHID (EP3). Chrome/Edge only.
category=Device Control
url=
architectures=ch32v
includes=WebHID.h
